[package]
name = "mayasaba-desktop"
version.workspace = true
edition.workspace = true
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2" }
mayasaba-core = { path = "../../../crates/core" }
mayasaba-protocol = { path = "../../../crates/protocol" }

[features]
custom-protocol = ["tauri/custom-protocol"]
